research_task:
  description: >
    Analyse the user query:{query} and provide answer by using the available tools.
  expected_output: >
    A list with bullet points on the answer of the user question
  agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
