# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst


research_task:
  description: >
    Conduct comprehensive data collection and analysis about {topic}
    Focus on gathering quantitative and qualitative data suitable 
    for in-depth statistical analysis and visualization.
    Make sure you find any interesting and relevant information given
    the current year is 2024
  expected_output: >
    A python code for visualization of the collected data and creating a blog-post with detailed 
    summary in mark down format.

  agent: researcher


reporting_task:
  description: >
    Execute the python code using the python_code_executor
  expected_output: >
    A detailed summary along with the generated image for a blog-post

    
      
  agent: reporting_analyst
